51:
  system_key: f
  key: "password_reset_subject_en"
  value: "Password recovery instructions"
53:
  system_key: f
  key: "password_reset_instructions_before_reset_url_en"
  value: "It has been requested a password reset for your account.
If you did not request to reset your password, please ignore this message.
If it was really you who requested to reset your password, click the following URL.
  "

54:
  system_key: f
  key: "password_reset_instructions_after_reset_url_en"
  value: "If the URL is not working, please try to copy and paste the URL in your browser.
If you still have problems resetting your password, please contact us.
  "
  80:
  system_key: f
  key: "account_notification_message_en"
  value: "Hi {first_name} {last_name},
You just created and verified successfully your account for wifi access.

You can now login and use the wifi service with username \"{username}\" and the password you chose during the registration phase.

You can monitor your use of the available traffic at the account management page:
{account_url}

If you ever forget your password, you can use the password reset procedure available at the following web address:
{password_reset_url}

Staff"
82:
  system_key: f
  key: "account_notification_subject_en"
  value: "New account created on [OpenWISP User Management System]"

