defaults: &defaults
  # registration form
  birth_date: false 
  address: false
  zip: false
  city: false
  state: false
  # other stuff
  send_email_notification_to_users: true
  automatic_captive_portal_login: true

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
